### ISSUE TITLE
This repo can't be cloned on windows.

### ISSUE THREAD

**Issue by guai** [radimk/nbgradle#1]
In windows 'aux' is a reserved filename and because of that there are errors while cloning:
error: Invalid path 'core/src/main/java/org/nbgradle/netbeans/project/lookup/aux/AuxiliaryConfigImpl.java'
Can you pls rename this dir?

**Comment by radimk** [comment]
fixed in https://github.com/radimk/nbgradle/commit/73b797fef5fb7147a5466e002da0d5c78de9f169
